plugins:
  - rubocop-rails
  - rubocop-migration
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance

Migration/AddCheckConstraint:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  Enabled: false
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Severity: refactor

Metrics/AbcSize:
  Severity: refactor

Rails/CreateTableWithTimestamps:
  Severity: refactor

Rails/HasManyOrHasOneDependent:
  Severity: refactor

Metrics/MethodLength:
  Severity: refactor
