require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/watches', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Watch. As you add validations to Watch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Watch.create! valid_attributes
      get watches_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      watch = Watch.create! valid_attributes
      get watch_url(watch)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_watch_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      watch = Watch.create! valid_attributes
      get edit_watch_url(watch)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Watch' do
        expect do
          post watches_url, params: { watch: valid_attributes }
        end.to change(Watch, :count).by(1)
      end

      it 'redirects to the created watch' do
        post watches_url, params: { watch: valid_attributes }
        expect(response).to redirect_to(watch_url(Watch.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Watch' do
        expect do
          post watches_url, params: { watch: invalid_attributes }
        end.not_to change(Watch, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post watches_url, params: { watch: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested watch' do
        watch = Watch.create! valid_attributes
        patch watch_url(watch), params: { watch: new_attributes }
        watch.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the watch' do
        watch = Watch.create! valid_attributes
        patch watch_url(watch), params: { watch: new_attributes }
        watch.reload
        expect(response).to redirect_to(watch_url(watch))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        watch = Watch.create! valid_attributes
        patch watch_url(watch), params: { watch: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested watch' do
      watch = Watch.create! valid_attributes
      expect do
        delete watch_url(watch)
      end.to change(Watch, :count).by(-1)
    end

    it 'redirects to the watches list' do
      watch = Watch.create! valid_attributes
      delete watch_url(watch)
      expect(response).to redirect_to(watches_url)
    end
  end
end
